package entity;
// Generated Dec 9, 2013 1:55:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Specialization generated by hbm2java
 */
public class Specialization  implements java.io.Serializable {


     private long specializationId;
     private String degree;
     private String name;
     private String process;
     private Set thesises = new HashSet(0);

    public Specialization() {
    }

	
    public Specialization(long specializationId, String degree, String name, String process) {
        this.specializationId = specializationId;
        this.degree = degree;
        this.name = name;
        this.process = process;
    }
    public Specialization(long specializationId, String degree, String name, String process, Set thesises) {
       this.specializationId = specializationId;
       this.degree = degree;
       this.name = name;
       this.process = process;
       this.thesises = thesises;
    }
   
    public long getSpecializationId() {
        return this.specializationId;
    }
    
    public void setSpecializationId(long specializationId) {
        this.specializationId = specializationId;
    }
    public String getDegree() {
        return this.degree;
    }
    
    public void setDegree(String degree) {
        this.degree = degree;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getProcess() {
        return this.process;
    }
    
    public void setProcess(String process) {
        this.process = process;
    }
    public Set getThesises() {
        return this.thesises;
    }
    
    public void setThesises(Set thesises) {
        this.thesises = thesises;
    }




}


