package entity;
// Generated Jan 5, 2014 6:06:06 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Specialization generated by hbm2java
 */
public class Specialization implements java.io.Serializable {

    private long specializationId;
    private String degree;
    private String name;
    private String process;
    private Set thesises = new HashSet(0);
    private Set thesises_1 = new HashSet(0);
    private Set cycles = new HashSet(0);

    public Specialization() {
    }
     
    public Specialization(String degree, String name, String process) {
        //this.specializationId = specializationId;
        this.degree = degree;
        this.name = name;
        this.process = process;
    }

    public Specialization(long specializationId, String degree, String name, String process) {
        this.specializationId = specializationId;
        this.degree = degree;
        this.name = name;
        this.process = process;
    }

    public Specialization(long specializationId, String degree, String name, String process, Set thesises, Set thesises_1, Set cycles) {
        this.specializationId = specializationId;
        this.degree = degree;
        this.name = name;
        this.process = process;
        this.thesises = thesises;
        this.thesises_1 = thesises_1;
        this.cycles=cycles;
    }

    public long getSpecializationId() {
        return this.specializationId;
    }

    public void setSpecializationId(long specializationId) {
        this.specializationId = specializationId;
    }

    public String getDegree() {
        return this.degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProcess() {
        return this.process;
    }

    public void setProcess(String process) {
        this.process = process;
    }

    public Set getThesises() {
        return this.thesises;
    }

    public void setThesises(Set thesises) {
        this.thesises = thesises;
    }

    public Set getThesises_1() {
        return this.thesises_1;
    }

    public void setThesises_1(Set thesises_1) {
        this.thesises_1 = thesises_1;
    }

    public Set getCycles() {
        return cycles;
    }

    public void setCycles(Set cycles) {
        this.cycles = cycles;
    }
}
