package entity;
// Generated Dec 9, 2013 1:55:34 PM by Hibernate Tools 3.2.1.GA

/**
 * Thesis generated by hbm2java
 */
public class Thesis implements java.io.Serializable {

    private long thesisId;
    private Specialization specialization;
    private Users users;
    private String title;
    private String description;
    private Boolean reserved;
    private Boolean confirmed;

    public Thesis() {
    }

    public Thesis(long thesisId, Specialization specialization, Users users, String title, String description) {
        this.thesisId = thesisId;
        this.specialization = specialization;
        this.users = users;
        this.title = title;
        this.description = description;
    }

    public Thesis(long thesisId, Specialization specialization, Users users, String title, String description, Boolean reserved, Boolean confirmed) {
        this.thesisId = thesisId;
        this.specialization = specialization;
        this.users = users;
        this.title = title;
        this.description = description;
        this.reserved = reserved;
        this.confirmed = confirmed;
    }

    public long getThesisId() {
        return this.thesisId;
    }

    public void setThesisId(long thesisId) {
        this.thesisId = thesisId;
    }

    public Specialization getSpecialization() {
        return this.specialization;
    }

    public void setSpecialization(Specialization specialization) {
        this.specialization = specialization;
    }

    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getReserved() {
        return this.reserved;
    }

    public void setReserved(Boolean reserved) {
        this.reserved = reserved;
    }

    public Boolean getConfirmed() {
        return confirmed;
    }

    public void setConfirmed(Boolean confirmed) {
        this.confirmed = confirmed;
    }
}

