package entity;
// Generated Dec 9, 2013 1:55:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long userId;
     private String login;
     private String password;
     private String licence;
     private String firstName;
     private String lastName;
     private Integer maxThesis;
     private String email;
     private Set thesises = new HashSet(0);

    public Users() {
    }

	
    public Users(long userId, String login, String password, String licence, String firstName, String lastName) {
        this.userId = userId;
        this.login = login;
        this.password = password;
        this.licence = licence;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Users(long userId, String login, String password, String licence, String firstName, String lastName, Integer maxThesis, String email, Set thesises) {
       this.userId = userId;
       this.login = login;
       this.password = password;
       this.licence = licence;
       this.firstName = firstName;
       this.lastName = lastName;
       this.maxThesis = maxThesis;
       this.email = email;
       this.thesises = thesises;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLicence() {
        return this.licence;
    }
    
    public void setLicence(String licence) {
        this.licence = licence;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public Integer getMaxThesis() {
        return this.maxThesis;
    }
    
    public void setMaxThesis(Integer maxThesis) {
        this.maxThesis = maxThesis;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getThesises() {
        return this.thesises;
    }
    
    public void setThesises(Set thesises) {
        this.thesises = thesises;
    }




}


