package entity;
// Generated Jan 5, 2014 6:06:06 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private long userId;
     private String login;
     private String password;
     private String licence;
     private String firstName;
     private String lastName;
     private long albumNumber;
     private String email;
     private CurrentPlan currentPlan;
     private Set thesisReservations = new HashSet(0);
     private Set thesises = new HashSet(0);
     private Set thesises_1 = new HashSet(0);
     private Set thesisHistory = new HashSet(0);

    public Set getThesisHistory() {
        return thesisHistory;
    }

    public void setThesisHistory(Set thesisHistory) {
        this.thesisHistory = thesisHistory;
    }

    public Users() {
    }

	
    public Users(long userId, String login, String password, String licence, String firstName, String lastName) {
        this.userId = userId;
        this.login = login;
        this.password = password;
        this.licence = licence;
        this.firstName = firstName;
        this.lastName = lastName;
    }
    public Users(long userId, String login, String password, String licence, String firstName, String lastName, long albumNumber, String email, Set thesisReservations, Set thesises, Set thesises_1,Set thesisHistory) {
       this.userId = userId;
       this.login = login;
       this.password = password;
       this.licence = licence;
       this.firstName = firstName;
       this.lastName = lastName;
       this.albumNumber = albumNumber;
       this.email = email;
       this.thesisReservations = thesisReservations;
       this.thesises = thesises;
       this.thesises_1 = thesises_1;
       this.thesisHistory = thesisHistory;
    }
   
    public long getUserId() {
        return this.userId;
    }
    
    public void setUserId(long userId) {
        this.userId = userId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getLicence() {
        return this.licence;
    }
    
    public void setLicence(String licence) {
        this.licence = licence;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public long getAlbumNumber() {
        return this.albumNumber;
    }
    
    public void setAlbumNumber(long albumNumber) {
        this.albumNumber = albumNumber;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getThesisReservations() {
        return this.thesisReservations;
    }
    
    public void setThesisReservations(Set thesisReservations) {
        this.thesisReservations = thesisReservations;
    }
    public Set getThesises() {
        return this.thesises;
    }
    
    public void setThesises(Set thesises) {
        this.thesises = thesises;
    }
    public Set getThesises_1() {
        return this.thesises_1;
    }
    
    public void setThesises_1(Set thesises_1) {
        this.thesises_1 = thesises_1;
    }
    public CurrentPlan getCurrentPlan() {
        return currentPlan;
    }

    public void setCurrentPlan(CurrentPlan currentPlan) {
        this.currentPlan = currentPlan;
    }
}


